# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline'], 'permissions': (('can_create_project', 'Manager'), ('is_member', 'Member'), ('is_leader', 'Leader'))},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_time_login',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='new_job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='new_project',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='new_task',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='viewed_job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='viewed_project',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='viewed_task',
        ),
        migrations.AddField(
            model_name='profile',
            name='unread_project',
            field=models.ManyToManyField(blank=True, null=True, related_name='unread_project', to='software.Project'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unread_task',
            field=models.ManyToManyField(blank=True, null=True, related_name='unread_task', to='software.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('Analysis', 'Analysis'), ('Code', 'Code'), ('Test', 'Test')], default='Analysis', help_text='Analysising', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('c', 'Coding'), ('t', 'Testing'), ('f', 'Fixing'), ('fi', 'Finish')], default='n', help_text='New task', max_length=2),
        ),
    ]
