# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import software.models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_auto_20171202_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='all_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='other_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='document',
            field=models.FileField(blank=True, help_text='Attach file here.', null=True, upload_to=software.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Enter a description of the project', max_length=2000),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('Analysis', 'Analysis'), ('Code', 'Code'), ('Test', 'Test')], default='Analysis', help_text='Choose the team which is responsibility for this stage. Ex: Analysis for new task or analysising task', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('a', 'Analysising'), ('c', 'Coding'), ('t', 'Testing'), ('f', 'Fixing'), ('w', 'Waiting'), ('fi', 'Finish')], default='n', help_text='Choose status for this task. Ex: New, Coding, Finish, etc.', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(help_text='Select types of the task', to='software.Type'),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='process',
            field=models.CharField(choices=[('Analysis', 'Analysis'), ('Code', 'Code'), ('Test', 'Test')], default='Analysis', help_text='Choose the team which is responsibility for this stage. Ex: Analysis for new task or analysising task', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='status',
            field=models.CharField(choices=[('n', 'New'), ('a', 'Analysising'), ('c', 'Coding'), ('t', 'Testing'), ('f', 'Fixing'), ('w', 'Waiting'), ('fi', 'Finish')], default='n', help_text='Choose status for this task. Ex: New, Coding, Finish, etc.', max_length=2),
        ),
    ]
