# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_auto_20171203_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline'], 'permissions': (('is_manager', 'Manager'), ('is_member', 'Member'), ('is_leader', 'Leader'))},
        ),
    ]
